services:
  - type: web
    name: riziki-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "waitress-serve --port=$PORT backend.core.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings