# Generated by Django 4.2.7 on 2026-05-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='passkey_assigned',
            field=models.BooleanField(default=False, help_text='Indicates whether a transactional passkey has been assigned to this user. Format: RZK followed by 4-8 numeric digits.'),
        ),
    ]
