# Generated by Django 4.2.7 on 2026-05-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_adminuser_passkey_assigned'),
        ('auth_app', '0002_adminuser_transaction_passkey'),
    ]

    operations = [
    ]
