# Generated by Django 4.2.7 on 2026-05-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_merge_20260529_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='transaction_passkey',
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='passkey_assigned',
            field=models.BooleanField(default=False, help_text='Indicates whether a transactional passkey has been assigned to this user.'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='passkey_revealed',
            field=models.BooleanField(default=False, help_text='Tracks whether the generated passkey has been revealed to the user at least once.'),
        ),
    ]
