# Generated by Django 4.2.7 on 2026-05-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_remove_adminuser_transaction_passkey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='passkey_plain',
            field=models.CharField(blank=True, help_text='Stored plain-text copy for administrative review.', max_length=10),
        ),
    ]
