# Generated by Django 4.2.7 on 2026-05-30 20:24

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_adminuser_passkey_plain'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='profile_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='passkey_plain',
            field=models.CharField(default=auth_app.models.generate_transaction_passkey, help_text='Stored plain-text copy for administrative review. Auto-generated on creation.', max_length=20),
        ),
    ]
