# Generated by Django 4.2.7 on 2026-05-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', models.CharField(blank=True, max_length=255)),
                ('consumer_secret', models.CharField(blank=True, max_length=255)),
                ('shortcode', models.CharField(blank=True, max_length=20)),
                ('passkey', models.CharField(blank=True, max_length=500)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('callback_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'M-Pesa Config',
                'db_table': 'mpesa_config',
            },
        ),
        migrations.CreateModel(
            name='ScheduledPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('STK_PUSH', 'STK Push'), ('B2C', 'B2C'), ('B2B', 'B2B')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('party_b', models.CharField(blank=True, max_length=20)),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Scheduled Payment',
                'verbose_name_plural': 'Scheduled Payments',
                'db_table': 'scheduled_payments',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
