# Generated by Django 4.2.7 on 2026-06-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesaconfig',
            name='environment',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='production', max_length=20),
        ),
    ]
